openplatform/account/urls.py
from django.conf.urls import url

from account.views import logout, qr_session, index

urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^qr_session/', qr_session, name='qr_session'),
    url(r'^logout/$', logout, name='logout'),
]

openplatform/assets/urls.py
from django.conf.urls import url

from assets.views import request_deposit, request_withdraw, deposit_process

urlpatterns = [
    url(r'^request_deposit/$', request_deposit, name='request_deposit'),
    url(r'^request_withdraw/$', request_withdraw, name='request_withdraw'),
    url(r'^deposit_process/$', deposit_process, name='deposit_process'),
]

openplatform/openplatform/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from account.views import home
from bixin.views import event_callback

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^assets/', include('assets.urls', namespace='assets')),
    url(r'^bot/', include('servicer.urls', namespace='servicer')),
    url(r'^event_callback', event_callback, name='event_callback'),
] + staticfiles_urlpatterns()

openplatform/servicer/urls.py
from django.conf.urls import url

from servicer.views import bot_callback, jssdk_detail, scheme_detail

urlpatterns = [
    url(r'^callback/', bot_callback, name='bot_callback'),
    url(r'^jssdk_detail/', jssdk_detail, name='jssdk_detail'),
    url(r'^scheme_detail/', scheme_detail, name='scheme_detail'),
]

openplatform/account/views.py
# -*- coding: utf-8 -*-
import time
import logging
from datetime import timedelta
import json
from urllib import urlencode

from django.conf import settings
from django.shortcuts import redirect, render
from django.core.urlresolvers import reverse

from bixin.helpers import utc_now
from bixin.client import Client
from bixin.decorators import login_required, tag_device
from bixin.models import QRSession, Fund
from bixin.helpers import ok_json, error_json
from bixin.bot import Bot
from bixin.helpers import ok_json, error_json

@tag_device
def home(request):
    if request.bx_user.is_authenticated():
        return redirect(reverse('account:index'))
    return render(request, 'home.html', locals())

@login_required
def index(request):
    user = request.bx_user
    funds = Fund.objects.filter(user=user)
    if not funds:
        fund = Fund.objects.create(user=user)
    else:
        fund = funds.first()

    return render(request, 'index.html', locals())

@tag_device
def qr_session(request):
    uuid = request.GET.get('uuid')
    sys_vendor_name = settings.APP_NAME
    if uuid:
        qr_info = uuid.split(':')
        if len(qr_info) < 2:
            return error_json('qr code format error')
        vendor_name, uuid = qr_info[:2]
        try:
            qr_session = QRSession.objects.get(uuid=uuid)
        except QRSession.DoesNotExist:
            return error_json('qr code not found')

        if vendor_name != sys_vendor_name:
            return error_json('vendor not match')

        elif qr_session.is_expired():
            return error_json('qr code expired')

        elif qr_session.user:
            request.session['site_userid'] = qr_session.user.id
            return ok_json(result='success')

        elif qr_session.user is None:
            return error_json('no user found')

        else:
            return error_json('fail')
    else:
        expire_seconds = 60 * 3
        qr_session = QRSession.objects.create(expired_at=utc_now() + timedelta(seconds=expire_seconds))

        QR_LOGIN_URL = settings.QR_LOGIN_URL
        protocol = "{}/qrcode/?uuid={}:{}".format(QR_LOGIN_URL, sys_vendor_name, qr_session.uuid)

        if request.from_device == 'phone':
            protocol = "bixin://login/confirm?{}".format(urlencode({'url': protocol}))

        resp = {
            'protocol': protocol,
            'expired_at': qr_session.expired_at.isoformat()
        }

    return ok_json(result=resp)

@login_required
def logout(request):
    request.session.flush()
    return redirect(reverse('home'))

openplatform/account/templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'js/qrcode.js' %}"></script>
    <script src="{% static 'js/bx_qr_code.js' %}"></script>
</head>
</html>

<body>
  <div class="container" center>
    <div class="row">
      <div class="col-md-8 col-md-offset-4">
        {% if request.from_device == 'phone' %}
          <div class="slogan" style="width: 60%">
            <h1>手机快捷登录Demo</h1>
          </div>
          <div class="login_button">
            <a href="" class="button" id="login_button"> 一键登录 </a>
          </div>
        {% else %}
        <div class="slogan" style="width: 60%">
          <h1>扫码登录Demo</h1>
        </div>
          <div class="qr-login">
              <div class="login_qrcode" id='bxQRCode'>
                <img src="{% static 'images/qr_refresh.png' %}" alt="Scan QR Login" class="bx-qr-code" width="160" id='bxQRCodeImage' onclick='javascript:init_qr_code("{% static "images/qr_refresh.png" %}", "{{ config.QR_LOGIN_URL }}");'>
              </div>
              </br>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
    <footer></footer>
</body>

<script>
init_qr_code("{% static 'images/qr_refresh.png' %}", "{{ config.QR_LOGIN_URL }}");
var from_device = "{{ request.from_device }}";
</script>


<style>
    .login_box {
    background: #fafbfb;
    text-align: center;
    padding-top: 20px;
    padding-bottom: 20px;
    .login_qrcode {
        margin-bottom: 10px;
    }
    a {
        text-decoration: none;
        color: $white;
        span {
            border-bottom: 1px solid #fafbfb;
        }
    }
}
.login_title {
    font-size: 16px;
    margin-bottom: 10px;
}

.login_button{
  font-size: 13px;
  background: #fff;
  border-radius: 4px;
  background: #fff;
  padding-left: 1px;
  padding-right: 1px;
  padding-top: 1px;
  padding-bottom: 2px;
  text-align: center; }
}

.dl-btn-qr{
  margin-top: 15px;
}
.dl-btn-qr-link{
  font-size: 14px;
  opacity: 0.6;
  margin-top: 0;
  margin-bottom: 0;
}

.header {
  background: #0166ff;
  padding-top: 20px;
}
</style>

openplatform/account/templates/index.html
{% load staticfiles bxtags %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/qrcode.js' %}"></script>
    <script src="{% static 'js/currency_deposit_or_withdraw.js' %}"></script>
</head>
</html>

<body>
  <div class="container" center>
    <div class="row">
      <div class="col-md-8 col-md-offset-4">
        <div class="slogan" style="width: 60%">
          <h2>恭喜你，已经成功登录</h2>
          <center>
            <a href="/account/logout/">退出</a>
          </center>
        </div>
      </div>
    </div>

    <div>
      <h3> 用户的详细信息 </h3>
      <p>
        userid: {{ user.userid }}
      </p>
      <p>
      username : {{ user.username }}
      </p>
      <p>
      target_id: {{ user.target_id }}
      </p>
      <p>
      BTC余额: {{ fund.balance|dformat}}
      </p>
    </div>
    <div>
      <h3> 网站扫码充值和提现 </h3>
      <p>
      <button class="btn btn-primary" onclick="create_deposit('BTC')"> BTC充值
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deposit_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">BTC充值Demo</h4>
          </div>
          <div class="modal-body">
            <center>
              <p>
              <img id='deposit_qr_code'/>
              </p>
              <p>
                请用Bixin App 扫码完成转账充值
              </p>
            </center>
          </div>
        </div>
      </div>
    </div>
      </p>
      <p>
      <button class="btn btn-primary" onclick="create_withdraw('BTC')"> BTC提现 </div>
        <!-- Modal -->
        <div class="modal fade" id="withdraw_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">BTC提现Demo</h4>
              </div>
              <div class="modal-body">
                  <label>提现BTC数量</label> <input name="amount" id="withdraw_amount"></input>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary" onclick="submit_withdraw()">确认提现</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      </p>
    <div class="container">
      <p>
        <a href="{% url 'servicer:jssdk_detail' %}"> 查看JS SDK 相关demo </a>
      </p>
      <p>
        <a href="{% url 'servicer:scheme_detail' %}"> 查看scheme 相关demo </a>
      </p>
    </div>
</body>